# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-01 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='definition',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='word',
            name='language',
            field=models.CharField(max_length=10),
        ),
    ]
