# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-02 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160301_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='translations',
            field=models.ManyToManyField(blank=True, to='api.Word'),
        ),
    ]
