# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-02 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_word_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='antonyms',
            field=models.ManyToManyField(blank=True, related_name='antonym', to='api.Word'),
        ),
        migrations.AddField(
            model_name='word',
            name='synonyms',
            field=models.ManyToManyField(blank=True, related_name='synonym', to='api.Word'),
        ),
        migrations.AlterField(
            model_name='word',
            name='definition',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='word',
            name='translations',
            field=models.ManyToManyField(blank=True, related_name='translation', to='api.Word'),
        ),
    ]
